### ISSUE TITLE
pmaint regen: reliably return errors when ebuilds die in global scope

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#103]
Long story short, I have no clue when `pmaint regen` actually exits with non-zero code but it seems to miss most of cache regen failures.

**Comment by radhermit** [comment]
I'm sort of guessing that it tries to keep going past all the bad ebuilds until it reaches the end if that's what you mean. That probably could be made configurable if it isn't already.

**Comment by mgorny** [comment]
No, that's fine and expected. Though I'd like it to reliably return non-zero exit status when at least one ebuild is failing in the repo.

**Comment by radhermit** [comment]
Ah, I see. That should be trivial to do, I'll check it out.

**Comment by radhermit** [comment]
Closing since I'm pretty sure this was fixed awhile ago when `pmaint regen` was reworked. Feel free to reopen with new info if you still hit issues.
