### ISSUE TITLE
pmerge: --debug does not apply to build operation exceptions

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#105]
Long story short,

```
$ pmerge -1 sys-libs/zlib --debug --verbose --debug
 * Resolving...
[...]

Forcing a clean of workdir

3 files required-
building sys-libs/zlib-1.2.8-r1
sandbox:stop  caught signal 15 in pid 18881
Sandboxed process killed by signal: Terminated
!!! caught exception building sys-libs/zlib-1.2.8-r1: Failed build operation: Executing phase setup: Caught exception: 'str' does not support the buffer interface
DEBUG pkgcore: ebp for pid '18881' appears dead, timing out
```

I would really love to see the backtrace here :).

**Comment by radhermit** [comment]
Hmm, I thought I fixed this a week or so ago. Must have missed something.

Also, not quite sure why you're specifying --debug twice, afaik pkgcore doesn't support multiple debug levels outside of manually specifying PKGCORE_DEBUG in env. However, combining the two so PKGCORE_DEBUG wouldn't have to be used much could be interesting so I might look into it.

**Comment by mgorny** [comment]
Just were trying randomly to get more output ;).
