### ISSUE TITLE
pmaint sync: no longer able to sync as non-root

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#123]
Long story short, the fix of conditionals/fallbacks in `_exec()` resulted in `setuid()` no longer ignoring UID 0 :). As a result, the default of syncing using root account is now passed through to _exec, effectively breaking syncing using non-root user.

**Comment by mgorny** [comment]
By the fix, I mean a5424040a400a8cb719697.

**Comment by radhermit** [comment]
Is there some reason pkgcore.sync.base.split_users() defaults to the root uid if the uri doesn't set a local user? Seems like the current process’s uid would make more sense in this case.
