### ISSUE TITLE
should make binpkg file creation atomic 

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcore#125]
System crashed while merging/creating binpkgs, pmerge outputted the following on next bootup:

Unhandled exception occurred:
 Metadata Exception: pkg built ebuild: app-shells/bash-4.3_p39, attr eapi_obj
 error: Metadata Exception: pkg built ebuild: app-shells/bash-4.3_p39, attr data
 error: xpak as malformed: not an xpak segment, trailer didn't match: <open file '/var/gentoo/packages/app-shells/bash-4.3_p39.tbz2', mode 'rb' at 0xe5fc4d30>

**Comment by ferringb** [comment]
It's possible something else is afoot, but the creation *is* atomic as far as I know- https://github.com/pkgcore/pkgcore/blob/master/pkgcore/binpkg/repo_ops.py#L97 .

**Comment by radhermit** [comment]
On 2015-09-01 17:04, ferringb wrote:
> It's possible something else is afoot, but the creation *is* atomic as
> far as I know-
> https://github.com/pkgcore/pkgcore/blob/master/pkgcore/binpkg/repo_ops.py#L97

I figured it probably was but that was the easiest (laziest) answer I
could think of at the time. :)

I'll try to come up with some steps to reproduce it and then look at the
binpkg output.

**Comment by ferringb** [comment]
Binpkg creation is atomic.  As to the original failure- on a guess, it relates to "system crashed while merging".  Ext4 from that era was known to leave empty files in place of 'written' content if a crash happened at the wrong time during the journal window.

That's my guess at least.  If the code isn't atomic, this definitely should be reopened w/ pointers to it.
