### ISSUE TITLE
pmaint regen: should remove stale cache entries

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#128]
Right now `pmaint regen` only creates/updates cache entries for packages. It should also remove stale entries (for removed ebuilds) so that the repository doesn't get cluttered.

**Comment by mgorny** [comment]
So I did some research, I have the following conclusions:

1. iterating over `cache` gives all cache entries, including those for removed packages, So we can't use it to figure out what to remove but we can use it to remove stuff.
2. iterating over `unconfigured_tree` gives only entries for existing packages and is pretty fast. It seems not to check metadata at all since it lists ebuilds which fail to source.

So the idea would be pretty much to get a set of cache entries, get a set of package entries from repo, get their difference and apply `del cache[x]` for the result.

Though I'm wondering -- performance-wise -- if it's better to just create two sets, and use set methods, or to create `frozenset` of packages, and do lookups while iterating over cache entries.

**Comment by ferringb** [comment]
Re: unconfigured_tree, you should iterate over *only* that for any cache cleanup- if you iterate over the configured tree, that 'configured' part is accept_license/accept_keywords/package.mask limited views of the unconfigured tree.  So you'd only maintain the parts of the tree that were configured viewable for the local domain.

Offhand, the fact that you had to dig down into the code to figure this out is probably a sign we should document that architecture bit somewhere.  Suggestions?

**Comment by mgorny** [comment]
Well, I never even considered configured tree, did I?

**Comment by radhermit** [comment]
On 2015-09-11 14:29, ferringb wrote:
> Offhand, the fact that you had to dig down into the code to figure
> this out is probably a sign we should document that architecture bit
> somewhere.  Suggestions?

We should probably have more descriptive docstrings for repo classes.

Adding some code examples in the docstrings or somewhere else (more
simple script examples?) along with explanations could help as well.

**Comment by radhermit** [comment]
I assume this is fixed since #129 was merged.
