### ISSUE TITLE
pmerge and profile.bashrc

### ISSUE THREAD

**Issue by joakim-tjernlund** [pkgcore/pkgcore#132]
pmerge-9999 complains:
/usr/local/portage/tmv3-target-overlay/profiles/cusfpv3/profile.bashrc: line 1: ./etc_file_list: No such file or directory
/usr/local/portage/tmv3-target-overlay/profiles/cusfpv3/profile.bashrc: line 1: ./etc_file_list: No such file or directory
/usr/local/portage/tmv3-target-overlay/profiles/cusfpv3/profile.bashrc: line 1: ./etc_file_list: No such file or directory
/usr/local/portage/tmv3-target-overlay/profiles/cusfpv3/profile.bashrc: line 1: ./etc_file_list: No such file or directory
/usr/local/portage/tmv3-target-overlay/profiles/cusfpv3/profile.bashrc: line 1: ./etc_file_list: No such file or directory
/usr/local/portage/tmv3-target-overlay/profiles/cusfpv3/profile.bashrc: line 1: ./etc_file_list: No such file or directory

in ../cusfpv3/profile.bashrc:
INSTALL_MASK="${INSTALL_MASK} $(. $(dirname "$*")/etc_file_list)"
export INSTALL_MASK

etc_file_list is present in the same dir as profile.bashrc

Works with portage, any suggestion how to change $(. $(dirname "$*")/etc_file_list) ?

**Comment by ferringb** [comment]
Yeah, that's not supposed to work in either.  You're relying on an implementation quirk in portage- the fact it invokes bashrc's via a _try_source "the-file-to-source".

**Comment by ferringb** [comment]
@zmedico : can you comment on this?  To be honest, I actually think what he's trying to do isn't bad, although I'd strongly argue that if a variable is exposed to the bashrc being sourced, it's the dirname rather than the file.

Assuming there is an agreement on what to do here, pkgcore could easily match that; however, we'd want to make damn sure the behaviour is recorded/updated into PMS else paludis may suffer the same breakage.

**Comment by zmedico** [comment]
Why not use ${BASH_SOURCE[0]} instead of $*, since that should work with any package manager?

**Comment by ferringb** [comment]
Makes sense, although it still feels like this may benefit from providing a
few expected variables to the scope....

**Comment by radhermit** [comment]
Is this closable then, or do we want to agree on some coordinated variable names to add to the scope?

**Comment by zmedico** [comment]
Generally, I'd prefer not to introduce a domain-specific variable when a standard bash variable is convenient enough. We've got enough domain-specific variables to document as it is.

**Comment by radhermit** [comment]
I generally agree, closing.
