### ISSUE TITLE
pmerge: parse_target() doesn't act as expected when passed PN::repo tokens in certain cases

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcore#133]
Specifically in the case where multiple packages share the same name and one is installed.

For example, it's expected that running something similar to:

pmerge -1av pkgname::repo

should try to rebuild cat-1/pkgname, where cat-1/pkgname::repo is installed and cat-2/pkgname::repo also exists but isn't installed. What's occurring now is that both matching pkgs are added to the list of targets to be passed to the resolver.

The problem is the section related to multiple restriction matches currently is only checking for PackageDep restrictions, but more basic boolean restrictions are created since the passed token isn't a proper pkg atom.

Furthermore, the check for matching installed pkgs will fail to find anything since it is checking for the repo to be equal to the source repository, but installed pkgs have 'vdb' for the basic 'repo' attr while the source repo is in the source_repository attr. Therefore the restriction will either have to be mangled before matching to switch the repo attrs, some vdb-specific match method will have to handle this case, or something similar along these lines.

**Comment by radhermit** [comment]
I think this should be fixed in cd30338 as well.

**Comment by radhermit** [comment]
Still need to fix the repository attr issue.

**Comment by den4ix** [comment]
Interestingly, why do you think it should go with rebuilding already installed pkg ? What if you actually intend to install app-vim/gnupg ? Current behaviour seems reasonable for me, or is it specified somewhere ?

**Comment by radhermit** [comment]
In order to match non-repo suffixed targets.

For example, merge app-crypt/gnupg and don't have app-vim/gnupg merged. Now try both `pmerge -1av gnupg` and `pmerge -1av gnupg::gentoo`. IMO, they both should have the same return value. Either they both should return that there are multiple matches or they should both resolve to the installed pkg.

It's not specifically documented yet in pkgcore docs I think, but a section could be added to the target section for pmerge relating that simple targets (without categories) resolve first to installed pkgs and then to the repo at large.

**Comment by den4ix** [comment]
Okay, I see, portage actully goes with the same strategy that is `pmerge gnupg::gentoo` behave the same way as `pmerge gnupg` rather than vice versa.
