### ISSUE TITLE
pkgcore wrongly assumes that 'sandbox' will be gentoo sandbox executable

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#137]
`/usr/bin/sandbox` is SELinux sandbox on Fedora. PkgCore tries to use it and fails in a very confusing way. I think that we need to verify that `sandbox` is actually what it expect to be. Plus rename our sandbox to fix this long-term.

**Comment by radhermit** [comment]
I expect adding proper prefix support to pkgcore could help fix cases like this.

**Comment by mgorny** [comment]
Adding proper imagination support to Gentoo developers would be more helpful ;-P.

**Comment by mgorny** [comment]
Will be replaced by pull request.
