### ISSUE TITLE
Support config directories

### ISSUE THREAD

**Issue by suhr** [pkgcore/pkgcore#173]
make.profile, package.mask{unmask,keyword}, etc.

Related issue: https://github.com/pkgcore/pkgcore/issues/78.

**Comment by radhermit** [comment]
I'm somewhat sure the only one missing is make.profile.

**Comment by radhermit** [comment]
Closing this since it's mostly a duplicate of #78, unless you can come up with config dirs besides make.profile that are unsupported and are specc-ed that they should be.
