### ISSUE TITLE
EbuildProcessor.is_alive(): does some crazy /proc/*/status lookups

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#177]
Long story short, it uses snakeoil's `process.is_running()`. That function does some random lookup for `/proc/*/status`, which is far from portable and even further from reliable. Well, I'm not sure but it looks like this may cause pretty funky results if ebuild processor dies and the PID is reused by another process.

I'm pretty sure pkgcore would be much happier doing proper process management with `SIGCHLD`, `os.wait()` and other nice stuff.

**Comment by ferringb** [comment]
this was resolved via the work started in 7a71d5d, the issue should be closed.
