### ISSUE TITLE
common.h missing

### ISSUE THREAD

**Issue by raacker** [pkgcore/pkgcore#186]
I have no idea if i installed snakeoil wrong. but I tried to install snakeoil many times and I couldn't finish installing pkgcore because it can't find snakeoil/common.h.

so i moved include/snakeoil directory to /usr/include manually and finished installing.

is there something wrong what i did during install those two?

For example, I installed new OS and pip install snakeoil and pkgcore. There was same error.

**Comment by radhermit** [comment]
What version of pip are you using? The headers are only properly installed with >=pip-6.1.0 (see https://github.com/pkgcore/snakeoil/issues/8).

**Comment by den4ix** [comment]
You might have run "python setup.py install install_headers" instead, (adding it to README) as setuptools doesn't install headers if you just pass install option. As radhermit said it works fine with >=pip-6.1.0, (pip 7.1.2 have done the job for me).

**Comment by radhermit** [comment]
Closing since I'm pretty sure this shouldn't be an issue anymore with recent pip and pkgcore suite releases.
