### ISSUE TITLE
[Errno 21] Is a directory: '/var/lib/layman/kde/profiles/package.mask'

### ISSUE THREAD

**Issue by devurandom** [pkgcore/pkgcore#197]
```
# pquery
Error in configuration:
 Failed instantiating default domain 'livefs'
 Failed instantiating section 'livefs'
 Failed instantiating section 'livefs': exception caught from 'pkgcore.ebuild.domain.domain'
 [Errno 21] Is a directory: '/var/lib/layman/kde/profiles/package.mask'
```

Portage does not complain about this and `package.mask` being a directory follows what is already possible in `/etc/portage/package.mask`. Thus it would be nice if pkgcore would support this, too.

I am using pkgcore-0.9.2.

**Comment by radhermit** [comment]
This is already supported it just requires enabling support in profile-formats. What does this overlay have for profile-formats in metadata/layout.conf?

**Comment by radhermit** [comment]
Ah, I think I see what's going on, the kde overlay only has portage-2 set in profile-formats; however, in pkgcore implementation this only enables relative paths for profile parent files (as read in portage.5). For directory-based masking/use flag settings, you have to add portage-1 for the pkgcore implementation to work.

Portage appears to cumulatively enable this when portage-2 is set, but the documentation isn't clear that is what should happen. Really this stuff should be added to PMS. :smile:

**Comment by radhermit** [comment]
As a further note, master appears to emulate portage behavior in treating portage-2 as a superset of portage-1 features, so you can update to that as well or wait for a release.

**Comment by radhermit** [comment]
Closing since this should be fixed in master.

**Comment by devurandom** [comment]
Thanks for the quick fix!
