### ISSUE TITLE
profiles/categories does not respect masters

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#206]
PMS sez, for files in the profiles dir including 'categories':

> If the repository is not intended to be stand-alone, the contents of these files are to be taken from or merged with the master repository as necessary.

FWICS, pkgcore just uses profiles/categories or guesses, instead of combining profiles/categories with masters. This breaks a lot of overlays that use profiles/categories to extend categories provided by ::gentoo.

**Comment by radhermit** [comment]
Just to note, pkgcore no longer falls back to the "default repo" when masters isn't explicitly set in metadata/layout.conf. In order words, overlays should always explicitly set masters if they're depending on eclasses, licenses, etc from the gentoo repo.
