### ISSUE TITLE
Support for EAPI=4-python and 5-progress

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#207]
Needed for the progress overlay. Without that, we're failing hard even at package names: https://qa-reports.gentoo.org/output/repos/progress.html

**Comment by radhermit** [comment]
To be honest, I don't want to support these. What is EAPI 6 missing that 4-python and 5-progress need?

**Comment by radhermit** [comment]
Closing as won't fix since this isn't going to happen. I'd rather improve error reporting and similar to help cases such as this. For example, I think cache regen-ing a repo should skip unknown EAPIs (possibly while throwing warnings).
