### ISSUE TITLE
d67100340d4a8221de breaks syncing!

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#210]
After applying d67100340d4a8221de, all repos instantly failed to sync, with errors like:

```
$ pmaint sync Armageddon
pmaint: error: Parsing failed: while loading portage config
initialization failed: lstat failed on location /home/mgorny/sync/R_Overlay
```

Long story short, you can't sync a single repository if at least one repository isn't synced yet :-P.

**Comment by mgorny** [comment]
And I'm pretty sure we were there before!

**Comment by radhermit** [comment]
Clearly it's past time to add some tests so I quit breaking it. :smile:
