### ISSUE TITLE
pkgcheck does to see metadata.xml in overlay-only categories

### ISSUE THREAD

**Issue by trofi** [pkgcore/pkgcore#212]
Tiny repository https://github.com/trofi/pkgcore-warts/tree/master/warts defines `warts` category with metadata.xml.
pkgcheck flags it as:
```
$ pkgcheck -r pkgcore-warts -o gentoo
...
unknown
  CatMissingMetadataXml: warts is missing metadata.xml
```

**Comment by radhermit** [comment]
Fixed, also the -o/--overlayed-repo option was dropped. Make sure masters are specified in the target repo instead if it's an overlay.
