### ISSUE TITLE
pkgcore no longer complains about no repo_name

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#213]
It seems that pkgcore has stopped complaining when repository doesn't have profiles/repo_name. Looking via the API, `repo_id` is set to match config section, and `repo_name` is always empty (even on repos with repo_name).

**Comment by mgorny** [comment]
Oh, I see 0d6311b52b06bfc1d31db40486ada443e7230c6d being at fault… I wonder how many new breakages I will discover after reverting it.

**Comment by mgorny** [comment]
Or maybe I should just add another attribute for the contents of that file. Probably pkgcore relies on repo_id being set internally.

**Comment by radhermit** [comment]
Re-added the warning, but note that two warnings for each unnamed repo will still be thrown. I have to figure out what's causing configs to be parsed twice and see if that can be fixed easily.

Also, attrs already existed and still do for the separate names. Use repo_name for profiles/repo_name or the repo-name field in metadata/layout.conf that overrides it, and config_name for the user specified repo name in repos.conf.

Finally repo_id defaults to config_name as that makes it more consistent for a user to override repo names without having to change the relevant files/settings in the repo itself.
