### ISSUE TITLE
handle more blockers automatically during dep resolution

### ISSUE THREAD

**Issue by 4eetah** [pkgcore/pkgcore#215]
For some reason pkgcore pulled out not the highest version (unlike portage) of kalarm available despite both kalarm-4.14.11_pre20160211 and kalarm-4.4.2016.01 are stable for amd64.
Also while facing resolution problems it doesn't provide meaningful info on how to resolve it:

```
!!! resolution failed
!!! request ( ( ('repo.livefs',) EqualityMatch: =False || ( ('category',) == virtual && ('package_is_real',) EqualityMatch: =False ) ) && =kde-apps/kalarm-4.14.11_pre20160211 ), mode none
!!! trying kde-apps/kalarm-4.14.11_pre20160211
!!!   request >=kde-apps/kdepim-common-libs-4.14.11_pre20160211:4[-aqua], mode depends
!!!   trying kde-apps/kdepim-common-libs-4.14.11_pre20160211
!!!     request >=kde-apps/kdepim-runtime-4.14.11_pre20160211:4[-aqua], mode rdepends
!!!     trying kde-apps/kdepim-runtime-4.14.11_pre20160211
!!!       request kde-frameworks/oxygen-icons:5, mode rdepends
!!!       trying kde-frameworks/oxygen-icons-5.21.0
!!!         request ( not (!kde-apps/kdepim-icons:4) && kde-apps/kdepim-icons ), mode none
!!!        failed due to rdepends blocker: !kde-apps/kdepim-icons:4 conflicts w/ [<MutatedPkg pkg=<<class 'pkgcore.ebuild.ebuild_built.package'> cpv='kde-apps/kdepim-icons-4.14.8' @0x7fc201bb0650> overrides=('depends', 'rdepends', 'post_rdepends') @0x7fc201b50e60>]
!!!        removing choices involving !kde-apps/kdepim-icons:4
!!!      removing choices involving kde-frameworks/oxygen-icons:5
!!!    removing choices involving >=kde-apps/kdepim-runtime-4.14.11_pre20160211:4[-aqua]
!!!  removing choices involving >=kde-apps/kdepim-common-libs-4.14.11_pre20160211:4[-aqua]

Failures encountered:
!!! failed '( ( ('repo.livefs',) EqualityMatch: =False || ( ('category',) == virtual && ('package_is_real',) EqualityMatch: =False ) ) && =kde-apps/kalarm-4.14.11_pre20160211 )'
potentials:
repo gentoo: [ ebuild src: kde-apps/kalarm-4.14.11_pre20160211 ]
```

while portage output is:

```
Calculating dependencies... done!
[ebuild  NS    ] kde-frameworks/oxygen-icons-5.21.0 [4.14.3] USE="{-test}" 
[uninstall     ] kde-apps/kdepim-icons-4.14.8 
[blocks b      ] kde-apps/kdepim-icons:4 ("kde-apps/kdepim-icons:4" is blocking kde-frameworks/oxygen-icons-5.21.0)
[ebuild     U  ] kde-apps/kdepimlibs-4.14.11_pre20160211 [4.14.10]
[ebuild     U  ] kde-apps/kdepim-runtime-4.14.11_pre20160211 [4.14.10]
[ebuild     U  ] kde-apps/kdepim-common-libs-4.14.11_pre20160211 [4.14.10]
[ebuild     U  ] kde-apps/kalarm-4.14.11_pre20160211 [4.14.8]
[blocks B      ] kde-frameworks/oxygen-icons:4 ("kde-frameworks/oxygen-icons:4" is blocking kde-frameworks/oxygen-icons-5.21.0)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (kde-frameworks/oxygen-icons-4.14.3:4/4.14::gentoo, installed) pulled in by
    kde-frameworks/oxygen-icons required by (kde-apps/kdepim-common-libs-4.14.11_pre20160211:4/4.14::gentoo, ebuild scheduled for merge)
    kde-frameworks/oxygen-icons required by (kde-apps/kalarm-4.14.11_pre20160211:4/4.14::gentoo, ebuild scheduled for merge)
...
```

**Comment by radhermit** [comment]
Currently the pkgcore resolver doesn't handle most of the cases involving blockers in an automatic fashion. In other words, if it hits a blocker for a certain version usually it will discard that version as a choice and try other available versions until it finds a match or fails out.

Yes, this should be fixed and the resolver basically needs to be reworked entirely in order to get away from adding more and more workarounds.

**Comment by joakim-tjernlund** [comment]
Just tried pmerge again and this time it didn't error out on me :)
The resolved pkgs was incomplete though so now I wonder if a rewrite of the
resolver is on the horizon?

**Comment by radhermit** [comment]
It's on my todo list that I'm slowly ticking through as my time/motivation allows.

**Comment by joakim-tjernlund** [comment]
Tried today again and now I get:
 pmerge -aNDv @world 
WARNING pkgcore: EAPI '7' isn't fully supported
 * Scanning for changed USE...
 * Resolving...
!!! resolution failed
!!! request ( ( ('repo.livefs',) EqualityMatch: =False || ( ('category',) == virtual && ('package_is_real',) EqualityMatch: =False ) ) && sys-boot/grub ), mode none

Failures encountered:
!!! failed '( ( ('repo.livefs',) EqualityMatch: =False || ( ('category',) == virtual && ('package_is_real',) EqualityMatch: =False ) ) && sys-boot/grub )'
potentials:
repo gentoo: [ ebuild src: sys-boot/grub-2.02-r3, ebuild src: sys-boot/grub-9999, ebuild src: sys-boot/grub-2.04_rc1 ]

FYI

**Comment by ferringb** [comment]
Closing this out since it's a mix of resolver issues.

The resolver *will* handle blockers, including exploring all possible ways around it.  If anyone finds an exception to that- where it doesn't explore all possible workarounds- please open a separate ticket.

As to the errors in this issue; they mostly come down to pkgcore not having full dependency support for EAPI5/7, and bugs along the way.  The resolver is (re)work in progress.
