### ISSUE TITLE
move plugin system into snakeoil and make more generic

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcore#224]
I think it would be handy if the plugin system was moved into snakeoil and made more generic. In addition, it seems like pplugincache functionality (regenerating plugin caches) could be moved to an option exposed by the standardized argparse class already in snakeoil.cli.arghparse so consuming cli tools would get something like a --regen-plugins option for their top level commands assuming regen functionality is still necessary/wanted after a move/partial rewrite.

**Comment by ferringb** [comment]
@arthurzam mind commenting on the status of plugins?

**Comment by arthurzam** [comment]
Plugins is currently deprecated, and in some releases will be removed at all.
