### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by oz123** [pkgcore/pkgcore#238]
@radhermit it's quite a while since the last tag, and it seems there tons of work being done.
Is there a change you upload a new version to pypi?

**Comment by radhermit** [comment]
I've been trying to corral a few more fixes and pullreqs into the the suite of interconnected packages (snakeoil/pkgcore/pkgcheck/pychroot). Most of the outstanding stuff should be done now with a few items remaining so hopefully I can get new releases out soon for all of them.

**Comment by radhermit** [comment]
Releases for snakeoil, pychroot, pkgcore, and pkgcheck are now all out on pypi (tarballs and wheels) and in the gentoo repo.
