### ISSUE TITLE
[PMS] src_test() should have unconditional S=${WORKDIR} fallback

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#243]
Don't ask me why but https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-1020009.1.8 doesn't make the fallback EAPI-conditional for `src_test`. Both Portage and Paludis do it unconditionally, so I think pkgcore should as well.

**Comment by radhermit** [comment]
With the spec change, I think this is fixed in https://github.com/pkgcore/pkgcore/commit/10cdad6cacb5fca562309b217f36cd459ef6d8c7
