### ISSUE TITLE
dodoc compresses files while in src_install ($D)

### ISSUE THREAD

**Issue by Enlik** [pkgcore/pkgcore#244]
PMS doesn't seem to be very specific, anyway it differs from Portage so it may break some assumptions that in $D files are not compressed after dodoc, so it may be considered to change. Also, quote:

> (me) ok, what I can see is that dodoc in pkgcore makes the file be compressed right
>         away, whilst in the case of portage, it's scheduled to do so (ecompress --queue)
> (Tim) portage does the queue stuff since it supports docompress

if so, it may be worth doing in any case.

**Comment by Enlik** [comment]
```
EAPI=6

DESCRIPTION=""
HOMEPAGE=""
SRC_URI=""

LICENSE=""
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}"

S="${WORKDIR}"

src_prepare() {
    default
    echo blah > file.txt
}

src_install() {
    dodoc file.txt
    find "${D}" || die 
}

```

```
ebuild haha-1.ebuild clean install
relevant file: /var/tmp/portage/app-misc/haha-1/image/usr/share/doc/haha-1/file.txt

pebuild haha-1.ebuild clean install
relevant file: /var/tmp/portage/app-misc/haha-1/image/usr/share/doc/haha-1/file.txt.bz2

> ebuild --version
Portage 2.3.24

> pebuild --version
pkgcore 0.9.7-gcab8504, Wed Sep 27 04:44:02 2017 -0400

also in 0.10.0-gafae76c
```

**Comment by mgorny** [comment]
Well, at least for EAPIs supporting controllable compression I dare say you can't really compress files before `src_install` finishes (because `docompress -x` may come after `dodoc` etc.)

**Comment by radhermit** [comment]
The issue is that pkgcore compresses after the ebuild/eclass specified src_install finishes but not before the externally visible result finishes because it wraps calling the user specified phases with its own internal phases. Thus, it could easily handle controllable compression in the same fashion if really wanted.
