### ISSUE TITLE
EAPI 7 stub needed

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#247]
Since EAPI 7 is coming really soon, we need enough stub to be able to generate metadata cache.

What we need:
- [ ] `BDEPEND` (at least to the point of writing final dependency string to cache),
- [ ] `eqawarn` function (trivial),
- [ ] version comparison functions (need to ask @ulm if agrees on relicensing them).

What we may want extra:
- [ ] `dostrip` stub that dies in global scope,
- [ ] `einfo` & co using stderr.

**Comment by radhermit** [comment]
I think this was closed when #246 was merged along with subsequent fixes for it. Remaining EAPI 7 support will be tracked individually and via the related milestone.
