### ISSUE TITLE
ARCH variable is different from Portage

### ISSUE THREAD

**Issue by Enlik** [pkgcore/pkgcore#251]
(This makes it unable to build wireguard, and perhaps any module.)

It seems that pkgcore's emake (?) sets different ARCH from what Portage does.

```
makefile {{{
all:
	echo "v=$(ARCH)"
}}}
```

case 1: nonempty ARCH

```
ebuild {{{
src_compile() {
    export ARCH=ble
    emake -f /tmp/mk
}
}}}
```

Portage 2.3.40-r1:
```
make -j4 -f /tmp/mk 
echo "v=ble"
v=ble
```

pkgcore 0.9.7:
```
echo "v=amd64"
v=amd64
```

case 2: ARCH not set in ebuild

Portage:
```
make -j4 -f /tmp/mk 
echo "v=amd64"
v=amd64
```

pkgcore:
```
echo "v="
v=
```

**Comment by mgorny** [comment]
Hmm, are your pastes correct? I find it entirely weird that pkgcore would override it to `amd64` when set to some random value, yet have it unset when unset originally.

That said, the Portage behavior pasted here is only somewhat correct. `ARCH` should be defined as part of `USE_EXPAND_UNPREFIXED` handling, provided that your profile sets the latter variable and you have `USE=amd64` enabled (also via profile). However, there's no guarantee that `ARCH` wouldn't be read-only, i.e. that ebuild will be allowed to override it in ebuild env.

**Comment by Enlik** [comment]
They should be (checked once again with pkgcore).

However, looking at the scope of changes since last tagged version, I should check with -9999… I will.

**Comment by Enlik** [comment]
So it is like this (note: emake is a separate script and runs through pkgcore-ebuild-helper (bash script) as per shebang):
- by default ARCH is `declare -- ARCH="amd64"` (set, not exported),
- if it is not exported in the ebuild:
  - it is not present in pkgcore-ebuild-helper's environment,
  - after sourcing ebd-env-transfer ($PKGCORE_EBD_ENV) in pkgcore-ebuild-helper, it stays unexported with the same value amd64,
  - unexported means empty in make;

- with `export ARCH=bla` in the ebuild:
  - now it is first `declare -x ARCH="bla"` in pkgcore-ebuild-helper,
  - again, ebd-env-transfer is sourced and makes it set to amd64,
  - but bash retains its "exported" status,
    - for example: `( export x=1; x=2; declare -p x )` makes exported x=2,
  - ARCH is exported (and has the value of amd64) and this is what goes to make.


Regarding this and Portage's behaviour mentioned above and your comment:                                   
being able to change ARCH is currently required by linux-info.elass which
does this, for example:

```bash
set_arch_to_kernel() { export ARCH=$(tc-arch-kernel); }
```

and a guess, commit 46c293c5cf79e0347314a6fee9602ddfc7b17279 might be the cause.

**Comment by Enlik** [comment]
w00t!
