### ISSUE TITLE
readthedocs.io documentation is out of date

### ISSUE THREAD

**Issue by daviessm** [pkgcore/pkgcore#289]
The [release notes on readthedocs.io](https://pkgcore.readthedocs.io/en/latest/news.html) shows v0.9.7 as the latest release.

**Comment by radhermit** [comment]
I've been slowly migrating various python projects from readthedocs to github pages deploys and pkgcore hasn't been migrated yet.

**Comment by radhermit** [comment]
Closing this since all pkgcore projects have been removed from rtd.

**Comment by oz123** [comment]
can you please add a link in the readme to correct and working pages in GitHub?

**Comment by thesamesam** [comment]
FWIW I think it's https://pkgcore.github.io/pkgcheck/ and friends.

**Comment by radhermit** [comment]
> can you please add a link in the readme to correct and working pages in GitHub?

I haven't fixed github doc deploys to gh-pages subdirs yet, but I'll add a link to it when it's done. It should end up as https://pkgcore.github.io/pkgcore if I can force github actions to do what I want. :smile:

**Comment by oz123** [comment]
These are the Docs for  pkgcheck, previously there where documents published for snakeoil and for pkgcore.
in theory these links should  work:

https://pkgcore.github.io/{pkgcore,snakeoil}

But for some reason I am getting a 404 error ...

Hence, the request  for explicitly linking the dogs in the readme.

**Comment by radhermit** [comment]
... I forgot to enable the gh-pages deploy option in the project settings. :laughing:

The design is still old and sucky, but at least now the site works.
