### ISSUE TITLE
restriction generation for atoms with USE flags is broken

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcore#292]
Currently generating an atom restriction for something like "cat/pkg[useflag]" returns a use restriction keyed off the ``use`` attribute which doesn't match any non-installed packages. To be useful as a restriction to match against non-vdb repos, it should instead match against the ``iuse`` attribute.

This will probably have to be some sort of multirestriction against both attrs in order to handle matching against both vdb and regular repos.

**Comment by ferringb** [comment]
I assume some shit got fixed in between, but this works now:
```
(env) ferringb@frith ~/gentoo/pkgcore $ pquery app-portage/gentoolkit[python_targets_python3_9] --attr use
app-portage/gentoolkit-0.5.0-r3 use="python_targets_python3_9 -python_targets_pypy3 -python_targets_python3_8 -test"
app-portage/gentoolkit-0.5.1-r1 use="python_targets_python3_10 python_targets_python3_9 -python_targets_pypy3 -python_targets_python3_8 -test"
app-portage/gentoolkit-0.6.1-r3 use="python_targets_python3_10 python_targets_python3_9 -python_targets_pypy3 -python_targets_python3_11 -python_targets_python3_8 -test"
```
