### ISSUE TITLE
Support for profiles/package.mask as a directory

### ISSUE THREAD

**Issue by a17r** [pkgcore/pkgcore#293]
...would be really nice as used in some overlays with extensive pre-release mask lists. Currently pkgcheck will fail like that:

``pkgcheck scan: error: failed parsing 'package.mask' in '...somedir/kde/profiles': [Errno 21] Is a directory: '...somedir/kde/profiles/package.mask'``

**Comment by radhermit** [comment]
Note that repos you want this enabled for will have to set something like ``profile-formats = portage-2`` in metadata/layout.conf otherwise they'll be treated with strict spec adherence if it's unset.
