### ISSUE TITLE
ERROR PORTAGE_BZIP2_COMMAND setting is invalid

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [pkgcore/pkgcore#302]
`sudo pmerge --ask --oneshot --buildpkg libcap` failed with
```
ERROR PORTAGE_BZIP2_COMMAND setting is invalid: 'pbzip2 --loadavg=13 --ignore-trailing-garbage '
PORTAGE_BZIP2_COMMAND setting from make.globals is invalid: 'bzip2'
```

While portage is fine with my pbzip2

**Comment by radhermit** [comment]
Closing this since PORTAGE_BZIP2_COMMAND is a portage-only setting (pkgcore disregards it entirely or you're running ancient pkgcore) and also because this doesn't appear to be an error from pkgcore.
