### ISSUE TITLE
pmaint regen is hanging randomly

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#307]
After upgrading pkgcore, `pmaint regen` on CI is now hanging randomly when upgrading some repos, effectively blocking the pipeline.

The most recent time it hanged on two repos.

```
 8768 10073 10073  6386 pts/0    10073 S+   60106   0:00  |                               \_ /bin/bash ./repos.bash
10073 10087 10073  6386 pts/0    10073 S+   60106   0:13  |                                   \_ /usr/lib/python-exec/python3.8/python /var/lib/repo-mirror-ci/repo-mirror-ci/repos/update-repos.py
10087 14194 10073  6386 pts/0    10073 S+   60106   0:05  |                                       \_ /usr/bin/python3.8 /usr/lib/python-exec/python3.8/pmaint --config /var/lib/repo-mirror-ci/data/etc/portage regen --use-local-desc --pkg-desc-index -t 32 johnmh
10087 10806 10073  6386 pts/0    10073 S+   60106   0:06  |                                       \_ /usr/bin/python3.8 /usr/lib/python-exec/python3.8/pmaint --config /var/lib/repo-mirror-ci/data/etc/portage regen --use-local-desc --pkg-desc-index -t 32 octopus
10806 19517 19517  6386 pts/0    10073 S    60106   0:00  |                                           \_ bash /bin/bash /usr/lib/pkgcore/ebd/ebuild-daemon.bash daemonize
19517 19520 19517  6386 pts/0    10073 S    60106   0:00  |                                           |   \_ /bin/bash /usr/lib/pkgcore/ebd/ebuild-daemon.bash daemonize
10806 28872 28872  6386 pts/0    10073 S    60106   0:00  |                                           \_ bash /bin/bash /usr/lib/pkgcore/ebd/ebuild-daemon.bash daemonize
28872 28880 28872  6386 pts/0    10073 S    60106   0:00  |                                           |   \_ /bin/bash /usr/lib/pkgcore/ebd/ebuild-daemon.bash daemonize
10806   416   416  6386 pts/0    10073 S    60106   0:00  |                                           \_ bash /bin/bash /usr/lib/pkgcore/ebd/ebuild-daemon.bash daemonize
  416   437   416  6386 pts/0    10073 S    60106   0:00  |                                           |   \_ /bin/bash /usr/lib/pkgcore/ebd/ebuild-daemon.bash daemonize
10806  9066  9066  6386 pts/0    10073 S    60106   0:00  |                                           \_ bash /bin/bash /usr/lib/pkgcore/ebd/ebuild-daemon.bash daemonize
 9066  9086  9066  6386 pts/0    10073 S    60106   0:00  |                                           |   \_ /bin/bash /usr/lib/pkgcore/ebd/ebuild-daemon.bash daemonize
10806 16713 10073  6386 pts/0    10073 S+   60106   0:00  |                                           \_ /usr/bin/python3.8 /usr/lib/python-exec/python3.8/pmaint --config /var/lib/repo-mirror-ci/data/etc/portage regen --use-local-desc --pkg-desc-index -t 32 octopus
```

`strace` isn't very helpful, the processes are either in `wait4()` or `futex()`.

**Comment by mgorny** [comment]
Bad news is that the 'last good' version is 0.11.2.

**Comment by mgorny** [comment]
0.11.5 is also affected, I can try intermediate versions during the day.

The actual hanging repos differ on every run, with the average of 2 repos hanging.

**Comment by mgorny** [comment]
...which is quite curious because I don't see anything that might cause this. I'm going to continue investigating.

**Comment by mgorny** [comment]
Ok, it was an ebuild difference:

```
--- 0.11.2/ebuild/processor.py	2021-05-09 11:28:47.914849747 +0000
+++ 0.11.3/ebuild/processor.py	2021-05-09 11:29:45.475694464 +0000
@@ -275,9 +275,6 @@ def chuck_KeyboardInterrupt(*args):
     raise KeyboardInterrupt("ctrl+c encountered")
 
 
-signal.signal(signal.SIGINT, chuck_KeyboardInterrupt)
-
-
 def chuck_TermInterrupt(ebp, *args):
     """Event handler for SIGTERM."""
     if ebp is None:
@@ -292,9 +289,6 @@ def chuck_TermInterrupt(ebp, *args):
         ebp.shutdown_processor()
 
 
-signal.signal(signal.SIGTERM, partial(chuck_TermInterrupt, None))
-
-
 def chuck_UnhandledCommand(ebp, line):
     """Event handler for unhandled commands."""
     raise UnhandledCommand(line)
@@ -332,6 +326,9 @@ class EbuildProcessor:
         self._outstanding_expects = []
         self._metadata_paths = None
 
+        signal.signal(signal.SIGTERM, partial(chuck_TermInterrupt, None))
+        signal.signal(signal.SIGINT, chuck_KeyboardInterrupt)
+
         if userpriv:
             self.__userpriv = True
             spawn_opts.update({
```

**Comment by mgorny** [comment]
...and I've confirmed that reverting this particular change causes pmaint not to hang anymore.

**Comment by mgorny** [comment]
Ok, I think that the problem is caused by the handler being set multiple times. If I restore the global setters and leave the ones in `__init__`, it also breaks. However, I seem to be able to get things working again if I make sure it's called only once. Will make a PR shortly.

**Comment by mgorny** [comment]
So given no better idea how to fix it, I see two easy options. Either:

1. We return to enabling them unconditionally, and make the pytest plugin use lazy/delayed imports, or
2. We require the API users to call some function to enable signal handlers early.

**Comment by radhermit** [comment]
> So given no better idea how to fix it, I see two easy options. Either:
> 
> 1. We return to enabling them unconditionally, and make the pytest plugin use lazy/delayed imports, or
> 2. We require the API users to call some function to enable signal handlers early.

3. Make sure signal handlers are only registered in the main thread (either using try/except or via conditionalizing).

I'm fairly sure this is happening when an ebd regen thread dies due to bash/ebuild/eclass failures which often causes a replacement thread to be spawned soon after. The new (non-main) thread then tries to set signal handlers on ebd init raising ValueError and causing a hang in some fashion.

**Comment by radhermit** [comment]
Should be fixed in https://github.com/pkgcore/pkgcore/commit/fcc786e9cef88a16e83932ef5cbc1090c01d4f32.

**Comment by mgorny** [comment]
And now we're back to having pytest broken by it.

**Comment by radhermit** [comment]
> And now we're back to having pytest broken by it.

I was under the impression that pytest was broken due to the same thread spawning issues, but I'm probably misremembering the error in that case. Anyway, slapping it back into ebd init with the conditional should be fine too.

**Comment by radhermit** [comment]
> No, the issue was that autoloading the pytest plugin causes signals to be overriden for random packages.

Should be fixed for that in git again already.
