### ISSUE TITLE
wrong website link in Gentoo wiki

### ISSUE THREAD

**Issue by ArneBab** [pkgcore/pkgcore#311]
The pkgcore page in Gentoo still links to the old pkgcore.org page instead of https://pkgcore.github.io/pkgcore/:

https://wiki.gentoo.org/wiki/Pkgcore

**Comment by radhermit** [comment]
I don't recall touching the wiki entry for it ever before, but I dropped the old pkgcore.org link for you. Feel free to edit the wiki yourself in the future since I don't think that page is locked to outside edits in any fashion. :smile:

**Comment by ArneBab** [comment]
Thank you! I don’t have my login ready and without login I only see "View source".
