### ISSUE TITLE
pmerge sets libdir to lib64 if no --libdir is given in the ebuild

### ISSUE THREAD

**Issue by oz123** [pkgcore/pkgcore#318]
I'm not sure if it's a real issue. `emerge` has a much larger and more extensive `econf` function which can handle
ebuilds that don't specify it.

Specifically, I encountered this issue when compiling postgresql with pmerge, and I was surprised to see a different result with emerge.

A more detail discussion can also be found in https://bugs.gentoo.org/806362.

**Comment by mgorny** [comment]
From Gentoo bug: https://projects.gentoo.org/pms/8/pms.html#x1-128002r2

I'll try to take a look at it today.

I presume that you're actually using pkgcore to install stuff? That's cool because I don't, and it's great to have someone actually testing that ;-).

**Comment by ulm** [comment]
Looks like a simple typo:
https://806362.bugs.gentoo.org/attachment.cgi?id=730080

**Comment by oz123** [comment]
@mgorny yes, i really like pkgcore it's solving dependencies much faster than portage. 
One critic I have is that error messages are not as friendly as with emerge.
