### ISSUE TITLE
move tests out of the pkgcore module namespace

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcore#33]
Tests should be moved into the root directory of the repo since we don't need to distribute and install them in the main module; however, note that there is some test code that should be kept in the pkgcore namespace since it's useful outside of the pure testing usecase (e.g. FakePkg). Not installing tests will probably become more important once we start reworking them and adding a lot more resolver tests, bash tests, and perhaps even integration style tests for pmerge, pinspect, etc.

Most of the test setup will have to be rewritten to support this but perhaps we can remove more snakeoil and pkgcore distutils hacks at the same time.

**Comment by ferringb** [comment]
Personally, I'd think installing the tests is worth it- it's a good way to do a sanity check as needed, and the space isn't that much.

What's the driving reason for this?  General cleanup, or...?

**Comment by radhermit** [comment]
Mostly I was trying to do general cleanup way back when. I agree with the sanity check stance and installing them is fine as long as they're not overly large.

This probably can be closed or changed to relate to simplifying/reworking the current setup.
