### ISSUE TITLE
ERROR pkgcore: invalid license group reference

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [pkgcore/pkgcore#335]
Runnng this `pquery -a --maintainer-email lssndrbarbieri@gmail.com --repo guru -n` spits out
```
ERROR pkgcore: invalid license group reference: 'FSF-APPROVED' in
             : <pkgcore.ebuild.repo_objs.Licenses object at 0x7464944f84a0>
ERROR pkgcore: invalid license group reference: 'OSI-APPROVED' in
             : <pkgcore.ebuild.repo_objs.Licenses object at 0x7464944f84a0>
```

**Comment by filmor** [comment]
The issue is (I think) that these license groups are not defined in the `guru` repo, only in the `gentoo` tree. Is this intended behaviour? Do all repos have to define all license groups that they are using?

**Comment by ulm** [comment]
> The issue is (I think) that these license groups are not defined in the `guru` repo, only in the `gentoo` tree. Is this intended behaviour? Do all repos have to define all license groups that they are using?

The `license_groups` file is beyond the scope of PMS, but is defined in [GLEP 23](https://www.gentoo.org/glep/glep-0023.html#license-groups). Which doesn't specify overlay behaviour:
> These groups are defined in a new file `license_groups` in the `profiles` subdirectory of the tree (or overlays). Details of handling groups defined in overlays is implementation dependent.

However, if we follow the [general principle outlined in PMS](https://projects.gentoo.org/pms/8/pms.html#x1-320004.4) for other files ...
> If the repository is not intended to be stand-alone, the contents of these files are to be taken from or merged with the master repository as necessary. 

... then Pkgcore should take the `license_groups` file from the master repository into account.

**Comment by arthurzam** [comment]
OK, I found a fix (surprisingly was very simple and short).
Currently working on writing a test so we can check the behavior was broken before and works now.

@Alessandro-Barbieri I tested with the line you specified, and it failed as you said, and after the fix is works now - so thank you for precise report with easy way to reproduce 😄
