### ISSUE TITLE
Improve eclass doc generation

### ISSUE THREAD

**Issue by arthurzam** [pkgcore/pkgcore#345]
The final target is a good generator used for `app-doc/eclass-manpages` and for `devmanual`.
There is a need for adding missing sections, and cleaning a lot of things!
ulm requested the output as DocBook output. There are existing RST to DocBook convertors.

## Resources:

- [eclass → manpage](https://github.com/mgorny/eclass-to-manpage)
- [manpage → html for devmanual](https://gitweb.gentoo.org/proj/devmanual.git/tree/bin/gen-eclass-html.sh#n145)
- [rst → dockbook using docutils](https://github.com/Abstrys/rst2db/blob/master/abstrys/docutils_ext/docbook_writer.py)
- [RST docutils spec](https://docutils.sourceforge.io/docs/user/rst/quickref.html#block-quotes)

## Bugs:

- https://bugs.gentoo.org/846503
- https://bugs.gentoo.org/773271
- https://github.com/pkgcore/pkgcore/issues/297

## Project name:
pkgcore's devmanual eclass doc pages generator (`pdedpg` for short)

**Comment by ulm** [comment]
> The final target is a good generator used for `app-doc/eclass-manpages` and for `devmanual`. There is a need for adding missing sections, and cleaning a lot of things! ulm requested the output as DocBook output. There are existing RST to DocBook convertors.

Not DocBook, but DevBook XML. See [human readable](https://devmanual.gentoo.org/appendices/devbook-guide/index.html) and [formal](https://gitweb.gentoo.org/proj/devmanual.git/plain/devbook.rnc) specs. It's a pretty simple format, especially when limited to eclass documentation, where there are no complicated elements like tables or figures.

If this should prove to be too difficult, then HTML would also be acceptable (after all, that's what we have now).

**Comment by arthurzam** [comment]
First of all, thank you @ulm for pointing me into the correct format (no idea how I managed to mistake docbook and devbook).
I'm now in the process of writing a translator from `rst` to `devbook` (your links to explanation and spec were spot on). It progresses not bad, and the remaining shouldn't be too hard.

I think if this finishes as intended, we will have a good `eclassdoc → {rst,manpage,devbook}` convertor. Then I think we can decide that eclassdoc is rst format (not so far from current state, and then devs can better format them). Finally, I guess I can do a traversal of the eclasses to improve the format of eclassdoc, to better confirm. Main issues I find:

- missing blank line between bullet list items.
- too big indent for second line of explanations in bullet lists, which make it mistake with a definition list.
