### ISSUE TITLE
Unable to search for maintainer-needed packages using pquery (`pquery --maintainer maintainer-needed`)

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcore#354]
Note that `pquery` has not had a `--maintainer-needed` (or `--orphaned` like `portageq`) option since 4cc83e54ae890680dcc4be7c5016c200fa4e3b45.

That commit mentions being able to use `--maintainer maintainer-needed` but this doesn't work for me:
```
$ pquery --maintainer maintainer-needed -r gentoo -n
[nothing]
```

I'd assumed this was related to the GLEP 63 changes in ~2016 but the commit dropped it in 2019, so it may have just broken since?

**Comment by arthurzam** [comment]
After checking the code, it indeed doesn't work currently. The current logic is that maintainer-needed packages have `maintainers` as empty tuple.

Do you prefer the return of `--maintainer-needed`, or that `--maintainer maintainer-needed` will work? I think the first one is better, but implementation wise there isn't a lot of difference.

**Comment by thesamesam** [comment]
I think I prefer `--maintainer maintainer-needed` for consistency, but it's not a strong feeling.

**Comment by arthurzam** [comment]
> I think I prefer `--maintainer maintainer-needed` for consistency, but it's not a strong feeling.

OK, this will be the way I do it. Fun fact, we have something there already, when empty value is passed, it checks for maintainer needed: https://github.com/pkgcore/pkgcore/blob/master/src/pkgcore/scripts/pquery.py#L782-L786
