### ISSUE TITLE
Spurious "empty" config file warnings

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#365]
```
WARNING:pkgcore:repos.conf: parsing '/etc/portage/repos.conf/eselect-repo.conf': file is empty
WARNING:pkgcore:repos.conf: parsing '/etc/portage/repos.conf/layman.conf': file is empty
WARNING:pkgcore:repos.conf: parsing '/etc/portage/repos.conf/mgorny.conf': file is empty
```

Firstly, they're not empty — they just have all lines commented out. Secondly, even if they were, what's wrong with that?

**Comment by ferringb** [comment]
> Firstly, they're not empty — they just have all lines commented out. Secondly, even if they were, what's wrong with that?

repos.conf generally shouldn't exist if it's empty content.  More to the point, it should *have* content, and my rough recollection is I made that a warning back in the google days when I added the md5 cache support.  I don't think that context will shake any counter-arguments lose, but that's my recollection.

**Comment by ferringb** [comment]
Turns out, not my doing: @arthurzam can you elaborate on https://github.com/pkgcore/pkgcore/commit/23eb4e077cfa94384e362f4161fa4a7d4dfebed9 ?

**Comment by ferringb** [comment]
My personal view is that we throw an error for a missing repos.conf, an  empty one is just the same thing (albeit with a better error message).

**Comment by thesamesam** [comment]
> > Firstly, they're not empty — they just have all lines commented out. Secondly, even if they were, what's wrong with that?
> 
> repos.conf generally shouldn't exist if it's empty content. More to the point, it should _have_ content, and my rough recollection is I made that a warning back in the google days when I added the md5 cache support. I don't think that context will shake any counter-arguments lose, but that's my recollection.

In this case, it's a directory, so it seems reasonable you might have some left-over ones you use every so often that you otherwise comment out. You might have a `crossdev.conf` which you sometimes comment out, but a `gentoo.conf` which is always active.

Having no valid files would be wrong though.

**Comment by ferringb** [comment]
@thesamesam or @mgorny what's your views on https://github.com/ferringb/pkgcore/commit/7236e076d3b3c394c06fc362f7fb05e2b238a942 ?

Effectively I bury @arthurzam 's original warning if the file doesn't exist. If the file exists and it has zero content, the warning still exists; not what you want @mgorny , but I suspect the argument is the file shouldn't exist in that state.

Either way, I figure my change is a step everyone agrees with, even if it's not enough to close this ticket.  Please ack/nack accordingly.

**Comment by thesamesam** [comment]
That works for me. We might want to think about https://bugs.gentoo.org/730502 again in future (https://wiki.gentoo.org/wiki/Pkgcheck#error:_repos.conf:_default_repo_.27gentoo.27_is_undefined_or_invalid) but I don't think that's a blocker for your fix at all.
