### ISSUE TITLE
pmerge: document --quiet support in --help

### ISSUE THREAD

**Issue by austin987** [pkgcore/pkgcore#37]

**Comment by radhermit** [comment]
Closing this since the pullreq was merged. I'll look at adding more output squelching if the option is enabled later on or submit more issues with what you'd like quiet to output or not output.

**Comment by austin987** [comment]
If I notice anything too verbose, I will. I didn't think it was supported at all at first glance, since I didn't see it in --help and so any other of portage's kitchen sink options weren't there either ;)
