### ISSUE TITLE
pmerge: add --sync support

### ISSUE THREAD

**Issue by austin987** [pkgcore/pkgcore#39]

**Comment by radhermit** [comment]
This is already provided by the pmaint utility, e.g. `pmaint sync gentoo` should sync the main gentoo repo via rsync. I'm not planning to add the --sync option to pmerge as I'm not a huge fan of emerge's all-encompassing options creep in general.

Also, I think in portage-2.2.16 and on they're adding sync support to emaint so you might want to get used to running *maint anyway. :)
