### ISSUE TITLE
snakeoil.bash.BashParseError  expecting '=' Sensitivity to space in make.conf 

### ISSUE THREAD

**Issue by oerisen** [pkgcore/pkgcore#405]
In make.conf settings if you use a space character before an equal sign as:
MAKEOPTS ="-j16"
pkgcore will give an  error like:
snakeoil.bash.BashParseError: error parsing '/etc/portage/make.conf' on or before line 20: err got token '', was expecting '='

If you remove the space between the equal sign ad parameter name pkgcore will continue as intended.

**Comment by thesamesam** [comment]
make.conf is parsed using shlex and such syntax isn't legal for strings in shell, so I'm not sure this is a bug.

**Comment by oerisen** [comment]
I agree it is not a bug, but it is undoubtedly an annoyance. Portage runs fine with spaces where pkgcore refuses to run.

**Comment by arthurzam** [comment]
pkgcore isn't fully compatible with portage on all **edge cases**. I think this space is an edge case. This isn't a valid bash variable set, and I see this more as a backward compatibility or even a misfeature by portage that it supports this extra space.

I don't think we will fix it.
