### ISSUE TITLE
setup.py: install options are ignored when passing multiple opts

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcore#43]
```
python setup.py \
    build_ext -I "${VIRTUAL_ENV}"/include/site/python2.7 \
    install --disable-man-pages --disable-html-docs
```

causes pkgcore to ignore the --disable-\* options. Passing the commands separately works.

**Comment by radhermit** [comment]
I'm not sure if this is a big deal anymore since the docs aren't built by default now.

**Comment by mgorny** [comment]
It's not a big deal but still a bug :).

**Comment by radhermit** [comment]
Closing as I think this has been fixed for a while now or at least trying:

./setup.py build --enable-man-pages install --enable-man-pages --mandir /home/foo/man --prefix /home/foo/bar

worked as expected for me.
