### ISSUE TITLE
pebuild: figure out how to dynamically pull available phases

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcore#47]
So we can have them outputted via the argparse error message if an unsupported one is passed as an argument.

**Comment by ferringb** [comment]
guessing this is in reference to pebuild?

Offhand, the defined_phases values on an ebuild should be accurate.  That value can't be accessed without appropriate cache validation/etc being done.

Or are you talking about a phase that isn't part of an EAPI spec?

**Comment by radhermit** [comment]
Yep, pebuild is in the issue title. ;)

Also, defined_phases clearly slipped my memory as that's basically what I'd want to start with.

**Comment by radhermit** [comment]
Pretty much done in 1e82633.
