### ISSUE TITLE
improve pplugincache failure message

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcore#76]
Currently the error message in pkgcore/plugin.py is lacking what namespace should be passed to pplugincache to manually regen the plugins, e.g. pkgcheck.plugins is needed when regenerating pkgcheck plugins, as well as some information relating to the failure reason.

**Comment by ferringb** [comment]
Pardon, not quite following this.  Are you saying the error message is crap for pplugincache?  Or that the exceptions thrown by the plugin machinery aren't namespace specific/clear?

**Comment by radhermit** [comment]
Mostly make the the error messages namespace specific so they work for pkgcheck users. Currently the message just says to run pplugincache which only regens the pkgcore namespace by default.

Or approach the issue in another way such as regenerating all namespaces when called with no argumetns.

**Comment by thesamesam** [comment]
See:
- https://github.com/pkgcore/pkgcore/commit/9b78522bac4ee386959caa59b3ce8d580fe497a6
- https://github.com/pkgcore/pkgcore/commit/b1079269328e5fad5e82ba4e33893cafeef4d132
- https://github.com/pkgcore/pkgcore/commit/76c71bcd13917e96e6937481d774a51bf3ebf82b
- https://github.com/pkgcore/pkgcore/commit/1a0f3aa7dcbc1464c56c16ac85ffb3d9ebdd5acb
- https://github.com/pkgcore/pkgcore/commit/816e3dee8d048386e753d7c0b618609b5489d25e
- https://github.com/pkgcore/pkgcore/issues/376
