### ISSUE TITLE
Funtoo support

### ISSUE THREAD

**Issue by suhr** [pkgcore/pkgcore#78]
Add Funtoo Linux support.

**Comment by radhermit** [comment]
You'll have to be more specific, I'm unsure what this even entails.

**Comment by suhr** [comment]
Funtoo portage have some differences from Gentoo portage (for example, http://www.funtoo.org/Funtoo_Profiles). So pkgcore needs additional support to work with Funtoo portage tree.

Btw, this error may be related (`make.profile` is a directory):

```
# pmerge 
Error in configuration:
 Parsing failed: while loading portage configuration
 '/etc/portage/make.profile must be a symlink pointing to a real target', callable unset!
 '/etc/portage/make.profile must be a symlink pointing to a real target', callable unset!
 [Errno 22] Invalid argument: '/etc/portage/make.profile'
```

**Comment by radhermit** [comment]
Ah right, and probably would require support for things like the noarch keywords (* and ~*) that portage historically supports.

Personally I have little interest adding support for such things unless they enter an EAPI at some point or can be externalized into loadable plugins written by other people. However, I'll leave this issue open for now in case others want to enumerate or discuss the required changes to make things work.

**Comment by radhermit** [comment]
Closing this since it's probably not going to happen unless it's supported by the spec or someone else does the work.
